### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by zbeez** [djtimca/rocketlaunchlive_api#1]
Hello, 

I get these errors in log since 2024.03 update

This error originated from a custom integration.

Logger: custom_components.rocketlaunchlive
Source: helpers/update_coordinator.py:331
integration: Rocket Launch Live - Next 5 Launches (documentation)
First occurred: 18:51:07 (1 occurrences)
Last logged: 18:51:07

Error requesting RocketLaunchLive data: Cannot connect to host fdo.rocketlaunch.live:443 ssl:default [Try again]

Any information how to sort that problem would be appreciated.

**Comment by djtimca** [comment]
Looks like a local issue to your install. That indicates your HA can’t access the source server. It is working fine for me.
